/**
 * Àṣàrò's rig, as data.
 *
 * GENERATED by design/_asaro2-data.js — do not hand-edit. The HTML prototype
 * (design/asaro-abstract.html) is generated from the same source, so the app
 * and the prototype cannot move differently.
 *
 * Keyframes are flattened into parallel numeric arrays because the animation
 * runs in Reanimated worklets on the UI thread, and a worklet wants arrays of
 * numbers rather than a tree of objects.
 */

export type AsaroAction = 'wave' | 'nod' | 'point' | 'thumbsUp' | 'celebrate' | 'shrug' | 'sigh' | 'think';
export type AsaroLook = 'cloth' | 'lockedIn';

export interface ActionTable {
    ms: number;
    t: number[];
    lx: number[]; ly: number[];
    rx: number[]; ry: number[];
    tip: number[]; bob: number[]; sq: number[];
}

export const ASARO_RIG = {
    "viewBox": "0 0 210 200",
    "bustBox": "42 32 126 126",
    "W": 210,
    "H": 200,
    "body": "M105 34 C147 34 168 64 168 106 C168 152 141 180 105 180 C69 180 42 152 42 106 C42 64 63 34 105 34 Z",
    "bodyCx": 105,
    "bodyCy": 107,
    "bodyRx": 63,
    "bodyRy": 73,
    "gaze": {
        "cx": 105,
        "cy": 97,
        "travelX": 13,
        "travelY": 9
    },
    "rings": [
        {
            "r": 10.5,
            "w": 3.4,
            "par": 1
        },
        {
            "r": 21,
            "w": 3,
            "par": 0.74
        },
        {
            "r": 32,
            "w": 2.6,
            "par": 0.5
        },
        {
            "r": 44,
            "w": 2.2,
            "par": 0.3
        },
        {
            "r": 57,
            "w": 1.8,
            "par": 0.16
        }
    ],
    "core": {
        "r": 5.4,
        "par": 1.08
    },
    "glint": {
        "dx": -2.6,
        "dy": -2.8,
        "r": 2.1,
        "par": 1.12
    },
    "tie": {
        "band": "M64 52 Q105 40 146 52 Q105 64 64 52 Z",
        "tails": [
            "M150 51 q13 -7 19 -19",
            "M150 55 q15 1 24 -6"
        ]
    },
    "hand": {
        "rx": 12.5,
        "ry": 9.5
    }
} as const;

/** Hand offsets from the body centre. Deliberately widened to number[]:
 *  worklets read these as plain numbers, and literal types fight assignment. */
export const ASARO_POSES: Record<string, { L: number[]; R: number[] }> = {
    "rest": {
        "L": [
            -58,
            30
        ],
        "R": [
            58,
            30
        ]
    },
    "waveUp": {
        "L": [
            -58,
            30
        ],
        "R": [
            66,
            -44
        ]
    },
    "waveOut": {
        "L": [
            -58,
            30
        ],
        "R": [
            82,
            -16
        ]
    },
    "point": {
        "L": [
            -58,
            30
        ],
        "R": [
            84,
            10
        ]
    },
    "thumbsUp": {
        "L": [
            -58,
            30
        ],
        "R": [
            50,
            -22
        ]
    },
    "celebrate": {
        "L": [
            -66,
            -44
        ],
        "R": [
            66,
            -44
        ]
    },
    "shrug": {
        "L": [
            -76,
            4
        ],
        "R": [
            76,
            4
        ]
    },
    "slump": {
        "L": [
            -50,
            48
        ],
        "R": [
            50,
            48
        ]
    },
    "hold": {
        "L": [
            -34,
            46
        ],
        "R": [
            34,
            46
        ]
    }
};

export const ASARO_ACTIONS: Record<AsaroAction, ActionTable> = {
    "wave": {
        "ms": 1650,
        "t": [
            0,
            0.18,
            0.36,
            0.54,
            0.72,
            0.88,
            1
        ],
        "lx": [
            -58,
            -58,
            -58,
            -58,
            -58,
            -58,
            -58
        ],
        "ly": [
            30,
            30,
            30,
            30,
            30,
            30,
            30
        ],
        "rx": [
            58,
            66,
            82,
            66,
            82,
            66,
            58
        ],
        "ry": [
            30,
            -44,
            -16,
            -44,
            -16,
            -44,
            30
        ],
        "tip": [
            0,
            -5,
            -3,
            -5,
            -3,
            -4,
            0
        ],
        "bob": [
            0,
            -5,
            -4,
            -5,
            -4,
            -3,
            0
        ],
        "sq": [
            1,
            1.03,
            1.01,
            1.03,
            1.01,
            1.02,
            1
        ]
    },
    "nod": {
        "ms": 1000,
        "t": [
            0,
            0.26,
            0.52,
            0.78,
            1
        ],
        "lx": [
            -58,
            -58,
            -58,
            -58,
            -58
        ],
        "ly": [
            30,
            30,
            30,
            30,
            30
        ],
        "rx": [
            58,
            58,
            58,
            58,
            58
        ],
        "ry": [
            30,
            30,
            30,
            30,
            30
        ],
        "tip": [
            0,
            0,
            0,
            0,
            0
        ],
        "bob": [
            0,
            8,
            -4,
            5,
            0
        ],
        "sq": [
            1,
            0.93,
            1.05,
            0.96,
            1
        ]
    },
    "point": {
        "ms": 1250,
        "t": [
            0,
            0.22,
            0.74,
            1
        ],
        "lx": [
            -58,
            -58,
            -58,
            -58
        ],
        "ly": [
            30,
            30,
            30,
            30
        ],
        "rx": [
            58,
            84,
            84,
            58
        ],
        "ry": [
            30,
            10,
            10,
            30
        ],
        "tip": [
            0,
            7,
            7,
            0
        ],
        "bob": [
            0,
            0,
            0,
            0
        ],
        "sq": [
            1,
            1.01,
            1.01,
            1
        ]
    },
    "thumbsUp": {
        "ms": 1300,
        "t": [
            0,
            0.2,
            0.76,
            1
        ],
        "lx": [
            -58,
            -58,
            -58,
            -58
        ],
        "ly": [
            30,
            30,
            30,
            30
        ],
        "rx": [
            58,
            50,
            50,
            58
        ],
        "ry": [
            30,
            -22,
            -22,
            30
        ],
        "tip": [
            0,
            3,
            3,
            0
        ],
        "bob": [
            0,
            -6,
            -5,
            0
        ],
        "sq": [
            1,
            1.04,
            1.03,
            1
        ]
    },
    "celebrate": {
        "ms": 1800,
        "t": [
            0,
            0.1,
            0.26,
            0.44,
            0.6,
            0.78,
            1
        ],
        "lx": [
            -58,
            -58,
            -66,
            -66,
            -66,
            -66,
            -58
        ],
        "ly": [
            30,
            30,
            -44,
            -44,
            -44,
            -44,
            30
        ],
        "rx": [
            58,
            58,
            66,
            66,
            66,
            66,
            58
        ],
        "ry": [
            30,
            30,
            -44,
            -44,
            -44,
            -44,
            30
        ],
        "tip": [
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        "bob": [
            0,
            7,
            -20,
            2,
            -13,
            1,
            0
        ],
        "sq": [
            1,
            0.88,
            1.12,
            0.96,
            1.08,
            0.98,
            1
        ]
    },
    "shrug": {
        "ms": 1450,
        "t": [
            0,
            0.28,
            0.72,
            1
        ],
        "lx": [
            -58,
            -76,
            -76,
            -58
        ],
        "ly": [
            30,
            4,
            4,
            30
        ],
        "rx": [
            58,
            76,
            76,
            58
        ],
        "ry": [
            30,
            4,
            4,
            30
        ],
        "tip": [
            0,
            6,
            6,
            0
        ],
        "bob": [
            0,
            -6,
            -6,
            0
        ],
        "sq": [
            1,
            0.94,
            0.94,
            1
        ]
    },
    "sigh": {
        "ms": 2000,
        "t": [
            0,
            0.28,
            0.6,
            0.86,
            1
        ],
        "lx": [
            -58,
            -58,
            -50,
            -50,
            -58
        ],
        "ly": [
            30,
            30,
            48,
            48,
            30
        ],
        "rx": [
            58,
            58,
            50,
            50,
            58
        ],
        "ry": [
            30,
            30,
            48,
            48,
            30
        ],
        "tip": [
            0,
            0,
            10,
            8,
            0
        ],
        "bob": [
            0,
            -7,
            9,
            7,
            0
        ],
        "sq": [
            1,
            1.06,
            0.9,
            0.92,
            1
        ]
    },
    "think": {
        "ms": 2200,
        "t": [
            0,
            0.25,
            0.55,
            0.8,
            1
        ],
        "lx": [
            -58,
            -34,
            -34,
            -34,
            -58
        ],
        "ly": [
            30,
            46,
            46,
            46,
            30
        ],
        "rx": [
            58,
            34,
            34,
            34,
            58
        ],
        "ry": [
            30,
            46,
            46,
            46,
            30
        ],
        "tip": [
            0,
            -9,
            9,
            -6,
            0
        ],
        "bob": [
            0,
            -3,
            -3,
            -2,
            0
        ],
        "sq": [
            1,
            1.02,
            1.02,
            1.01,
            1
        ]
    }
};

export const ASARO_LOOKS: Record<AsaroLook, {
    bodyHi: string; bodyLo: string; ring: string; core: string; rim: string;
    tie: string; hand: string; handHi: string; tieVisible: boolean; ringCount: number;
}> = {
    "cloth": {
        "bodyHi": "#22385a",
        "bodyLo": "#11203a",
        "ring": "#c9762c",
        "core": "#efe6d8",
        "rim": "rgba(9,18,34,0.55)",
        "tie": "#c9762c",
        "hand": "#17263f",
        "handHi": "rgba(255,255,255,0.14)",
        "tieVisible": true,
        "ringCount": 5
    },
    "lockedIn": {
        "bodyHi": "#131313",
        "bodyLo": "#000000",
        "ring": "#ffffff",
        "core": "#ffffff",
        "rim": "rgba(255,255,255,0.34)",
        "tie": "#ffffff",
        "hand": "#ffffff",
        "handHi": "rgba(0,0,0,0.18)",
        "tieVisible": false,
        "ringCount": 3
    }
};
